version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 173.70.1.0/24

services:

  php:
    container_name: work_king_php
    build:
      context: docker/php
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 173.70.1.3
      DB_PORT: 3306
      DB_DATABASE: work_king
      DB_USERNAME: root
      DB_PASSWORD: secret
    volumes:
      - .:/opt/work_king:cached
    networks:
      default:
         ipv4_address: 173.70.1.2

  mysql:
    container_name: work_king_mysql
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: work_king
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql:/var/lib/mysql:cached
    ports:
      - 3307:3306
    networks:
      default:
         ipv4_address: 173.70.1.3

  web:
    container_name: work_king_web
    image: nginx:latest
    volumes:
      - ./:/opt/work_king:cached
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
    ports:
      - 8080:8080
    networks:
      default:
         ipv4_address: 173.70.1.4


  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://173.70.1.4:8080/v1/docs/swagger.yaml
    ports:
      - "7080:8080"
    networks:
      default:
        ipv4_address: 173.70.1.5

